sudo: required

language: node_js
node_js:
  - '10'

services:
    - docker

before_install:
    - docker build -t imagename/docker-react -f thirdapp/Dockerfile.dev thirdapp/

script:
    - docker run imagename/docker-react npm run test -- --coverage
